spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.thirdlucky.org.apache.dubbo.provider.service
  protocol:
    name: dubbo
    port: 28820
    serialization: kryo
  registry:
    address: nacos://192.168.227.132:8848
  provider:
    loadbalance: roundrobin